-- ============================================================================
--  CORE EMISOR DE TARJETAS + MÓDULO DE CRÉDITO
--  Esquema de base de datos — PostgreSQL (Neon)
--  Fase 0 — Cimientos: clientes, cuentas, tarjetas, ledger de doble partida,
--           crédito, facturación, pagos, seguridad y auditoría.
--
--  Ejecutar en una base limpia:  psql "$DATABASE_URL" -f db/schema.sql
-- ============================================================================

BEGIN;

-- Para gen_random_uuid()
CREATE EXTENSION IF NOT EXISTS pgcrypto;

-- ────────────────────────────────────────────────────────────────────────────
--  CATÁLOGOS
-- ────────────────────────────────────────────────────────────────────────────
CREATE TABLE productos (
  id            UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  nombre        TEXT NOT NULL,
  tipo          TEXT NOT NULL CHECK (tipo IN ('DEBITO','CREDITO')),
  moneda        CHAR(3) NOT NULL DEFAULT 'USD',
  bin           TEXT NOT NULL,
  tasa_interes  NUMERIC(7,4),               -- anual (solo crédito), ej. 0.3600 = 36%
  dia_corte     INT CHECK (dia_corte BETWEEN 1 AND 31),
  dias_pago     INT,                         -- días de gracia hasta fecha de pago
  comision_anual NUMERIC(18,2) DEFAULT 0,
  activo        BOOLEAN NOT NULL DEFAULT true,
  creado_en     TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- ────────────────────────────────────────────────────────────────────────────
--  CLIENTES (titulares)
-- ────────────────────────────────────────────────────────────────────────────
CREATE TABLE clientes (
  id            UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  documento     TEXT NOT NULL,
  nombre        TEXT NOT NULL,
  email         TEXT,
  telefono      TEXT,
  estado        TEXT NOT NULL DEFAULT 'ACTIVO'   CHECK (estado IN ('ACTIVO','BLOQUEADO','CERRADO')),
  kyc_estado    TEXT NOT NULL DEFAULT 'PENDIENTE' CHECK (kyc_estado IN ('PENDIENTE','REVISION','VERIFICADO','RECHAZADO')),
  creado_en     TIMESTAMPTZ NOT NULL DEFAULT now(),
  UNIQUE (documento)
);

-- ────────────────────────────────────────────────────────────────────────────
--  CUENTAS
-- ────────────────────────────────────────────────────────────────────────────
CREATE TABLE cuentas (
  id            UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  cliente_id    UUID NOT NULL REFERENCES clientes(id),
  producto_id   UUID NOT NULL REFERENCES productos(id),
  tipo          TEXT NOT NULL CHECK (tipo IN ('DEBITO','CREDITO')),
  moneda        CHAR(3) NOT NULL DEFAULT 'USD',
  estado        TEXT NOT NULL DEFAULT 'ACTIVA' CHECK (estado IN ('ACTIVA','BLOQUEADA','CERRADA')),
  creado_en     TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX idx_cuentas_cliente ON cuentas(cliente_id);

-- ────────────────────────────────────────────────────────────────────────────
--  TARJETAS  (el PAN NUNCA en claro: solo token al vault + últimos 4)
-- ────────────────────────────────────────────────────────────────────────────
CREATE TABLE tarjetas (
  id            UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  cuenta_id     UUID NOT NULL REFERENCES cuentas(id),
  pan_token     TEXT NOT NULL,               -- referencia al PCI vault
  pan_ultimos4  CHAR(4) NOT NULL,
  vencimiento   CHAR(4) NOT NULL,            -- YYMM
  estado        TEXT NOT NULL DEFAULT 'ACTIVA' CHECK (estado IN ('ACTIVA','BLOQUEADA','CANCELADA')),
  es_virtual    BOOLEAN NOT NULL DEFAULT false,
  creado_en     TIMESTAMPTZ NOT NULL DEFAULT now(),
  UNIQUE (pan_token)
);
CREATE INDEX idx_tarjetas_cuenta ON tarjetas(cuenta_id);

-- ════════════════════════════════════════════════════════════════════════════
--  LEDGER DE DOBLE PARTIDA
--  Cada transacción = 1 asiento con N movimientos que SUMAN CERO.
-- ════════════════════════════════════════════════════════════════════════════
CREATE TABLE asientos (
  id            UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  request_id    TEXT UNIQUE NOT NULL,        -- idempotencia: reintentos no duplican
  tipo          TEXT NOT NULL CHECK (tipo IN ('COMPRA','PAGO','INTERES','COMISION','REVERSO','AJUSTE')),
  referencia    TEXT,
  creado_en     TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- Particionada por fecha para soportar alto volumen.
-- PK debe incluir la clave de partición (creado_en).
CREATE TABLE movimientos (
  id            BIGINT GENERATED BY DEFAULT AS IDENTITY,
  asiento_id    UUID NOT NULL REFERENCES asientos(id),
  cuenta_id     UUID NOT NULL REFERENCES cuentas(id),
  monto         NUMERIC(18,2) NOT NULL,      -- (+) débito / (-) crédito
  moneda        CHAR(3) NOT NULL DEFAULT 'USD',
  creado_en     TIMESTAMPTZ NOT NULL DEFAULT now(),
  PRIMARY KEY (id, creado_en)
) PARTITION BY RANGE (creado_en);

-- Particiones mensuales (en producción: automatizar con pg_partman)
CREATE TABLE movimientos_2026_06 PARTITION OF movimientos
  FOR VALUES FROM ('2026-06-01') TO ('2026-07-01');
CREATE TABLE movimientos_2026_07 PARTITION OF movimientos
  FOR VALUES FROM ('2026-07-01') TO ('2026-08-01');
CREATE TABLE movimientos_2026_08 PARTITION OF movimientos
  FOR VALUES FROM ('2026-08-01') TO ('2026-09-01');

CREATE INDEX idx_mov_2026_06_cuenta ON movimientos_2026_06(cuenta_id, creado_en);
CREATE INDEX idx_mov_2026_07_cuenta ON movimientos_2026_07(cuenta_id, creado_en);
CREATE INDEX idx_mov_2026_08_cuenta ON movimientos_2026_08(cuenta_id, creado_en);

-- ────────────────────────────────────────────────────────────────────────────
--  VALIDACIÓN: los movimientos de un asiento deben SUMAR CERO (doble partida)
--  Trigger diferido: se valida al confirmar la transacción (COMMIT).
-- ────────────────────────────────────────────────────────────────────────────
CREATE OR REPLACE FUNCTION valida_asiento_balanceado() RETURNS trigger AS $$
DECLARE
  total NUMERIC(18,2);
BEGIN
  SELECT COALESCE(SUM(monto),0) INTO total
    FROM movimientos WHERE asiento_id = NEW.asiento_id;
  IF total <> 0 THEN
    RAISE EXCEPTION 'Asiento % no balanceado (suma = %). Debe ser 0.', NEW.asiento_id, total;
  END IF;
  RETURN NULL;
END;
$$ LANGUAGE plpgsql;

CREATE CONSTRAINT TRIGGER trg_asiento_balanceado
  AFTER INSERT ON movimientos
  DEFERRABLE INITIALLY DEFERRED
  FOR EACH ROW EXECUTE FUNCTION valida_asiento_balanceado();

-- ────────────────────────────────────────────────────────────────────────────
--  SALDOS (materializado para lectura O(1); se actualiza por trigger)
-- ────────────────────────────────────────────────────────────────────────────
CREATE TABLE saldos (
  cuenta_id     UUID PRIMARY KEY REFERENCES cuentas(id),
  saldo         NUMERIC(18,2) NOT NULL DEFAULT 0,
  actualizado_en TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE OR REPLACE FUNCTION actualiza_saldo() RETURNS trigger AS $$
BEGIN
  INSERT INTO saldos (cuenta_id, saldo, actualizado_en)
  VALUES (NEW.cuenta_id, NEW.monto, now())
  ON CONFLICT (cuenta_id)
  DO UPDATE SET saldo = saldos.saldo + NEW.monto, actualizado_en = now();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trg_actualiza_saldo
  AFTER INSERT ON movimientos
  FOR EACH ROW EXECUTE FUNCTION actualiza_saldo();

-- ════════════════════════════════════════════════════════════════════════════
--  CRÉDITO
-- ════════════════════════════════════════════════════════════════════════════
CREATE TABLE lineas_credito (
  id              UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  cuenta_id       UUID NOT NULL UNIQUE REFERENCES cuentas(id),
  limite          NUMERIC(18,2) NOT NULL CHECK (limite >= 0),
  disponible      NUMERIC(18,2) NOT NULL,     -- limite - usado - autorizado(hold)
  tasa_interes    NUMERIC(7,4) NOT NULL,
  estado          TEXT NOT NULL DEFAULT 'ACTIVA' CHECK (estado IN ('ACTIVA','SUSPENDIDA','CANCELADA')),
  actualizado_en  TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- Autorizaciones (holds) — alto volumen → particionada por fecha
CREATE TABLE autorizaciones (
  id            UUID DEFAULT gen_random_uuid(),
  tarjeta_id    UUID NOT NULL REFERENCES tarjetas(id),
  monto         NUMERIC(18,2) NOT NULL,
  stan          TEXT,                          -- DE11
  rrn           TEXT,                          -- DE37
  de39          CHAR(2),                       -- código de respuesta
  estado        TEXT NOT NULL CHECK (estado IN ('APROBADA','RECHAZADA','REVERSADA','LIQUIDADA')),
  creado_en     TIMESTAMPTZ NOT NULL DEFAULT now(),
  PRIMARY KEY (id, creado_en)
) PARTITION BY RANGE (creado_en);

CREATE TABLE autorizaciones_2026_06 PARTITION OF autorizaciones
  FOR VALUES FROM ('2026-06-01') TO ('2026-07-01');
CREATE TABLE autorizaciones_2026_07 PARTITION OF autorizaciones
  FOR VALUES FROM ('2026-07-01') TO ('2026-08-01');
CREATE TABLE autorizaciones_2026_08 PARTITION OF autorizaciones
  FOR VALUES FROM ('2026-08-01') TO ('2026-09-01');

CREATE INDEX idx_auth_2026_06 ON autorizaciones_2026_06(tarjeta_id, creado_en);
CREATE INDEX idx_auth_2026_07 ON autorizaciones_2026_07(tarjeta_id, creado_en);
CREATE INDEX idx_auth_2026_08 ON autorizaciones_2026_08(tarjeta_id, creado_en);

CREATE TABLE ciclos_facturacion (
  id             UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  cuenta_id      UUID NOT NULL REFERENCES cuentas(id),
  fecha_corte    DATE NOT NULL,
  fecha_pago     DATE NOT NULL,
  saldo_anterior NUMERIC(18,2) NOT NULL DEFAULT 0,
  saldo_nuevo    NUMERIC(18,2) NOT NULL DEFAULT 0,
  pago_minimo    NUMERIC(18,2) NOT NULL DEFAULT 0,
  intereses      NUMERIC(18,2) NOT NULL DEFAULT 0,
  comisiones     NUMERIC(18,2) NOT NULL DEFAULT 0,
  estado         TEXT NOT NULL DEFAULT 'ABIERTO' CHECK (estado IN ('ABIERTO','CERRADO','PAGADO','MORA')),
  creado_en      TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX idx_ciclos_cuenta ON ciclos_facturacion(cuenta_id, fecha_corte);

CREATE TABLE pagos (
  id            UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  cuenta_id     UUID NOT NULL REFERENCES cuentas(id),
  monto         NUMERIC(18,2) NOT NULL CHECK (monto > 0),
  canal         TEXT,                          -- TRANSFERENCIA|EFECTIVO|TARJETA|...
  asiento_id    UUID REFERENCES asientos(id),  -- enlace al ledger
  creado_en     TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX idx_pagos_cuenta ON pagos(cuenta_id, creado_en);

-- ════════════════════════════════════════════════════════════════════════════
--  SEGURIDAD / AUDITORÍA
-- ════════════════════════════════════════════════════════════════════════════
CREATE TABLE usuarios (
  id            UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  username      TEXT UNIQUE NOT NULL,
  nombre        TEXT,
  password_hash TEXT NOT NULL,
  rol           TEXT NOT NULL CHECK (rol IN ('ADMIN','OPERADOR','FINANZAS','RIESGO','AUDITOR')),
  estado        TEXT NOT NULL DEFAULT 'ACTIVO' CHECK (estado IN ('ACTIVO','INACTIVO')),
  creado_en     TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE auditoria (
  id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  usuario_id    UUID,
  accion        TEXT NOT NULL,
  entidad       TEXT,
  entidad_id    TEXT,
  detalle       JSONB,
  creado_en     TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX idx_auditoria_fecha ON auditoria(creado_en);

COMMIT;

-- ============================================================================
--  NOTAS DE OPERACIÓN
--  • Saldo de cuenta:           SELECT saldo FROM saldos WHERE cuenta_id = ?;
--  • Toda escritura de dinero:  1 INSERT en 'asientos' + N INSERT en
--    'movimientos' que sumen 0, dentro de UNA transacción.
--  • Idempotencia:              usar 'request_id' único por operación.
--  • Particiones:               crear nuevas cada mes (pg_partman recomendado).
--  • PAN:                       jamás en claro; solo 'pan_token' + 'pan_ultimos4'.
-- ============================================================================
